version: "3.7"

services:
  web:
    image: node:18-alpine
    container_name: v2ray-ui
    working_dir: /app
    volumes:
      - ${APP_DATA_DIR}/app:/app
    command: sh -c "npm install && npx ts-node ."
    ports:
      - "4000:4000"
    restart: always