version: "3.7"

services:
  server:
    image: node:18-alpine
    container_name: calopoly-server
    working_dir: /app
    volumes:
      - ${APP_DATA_DIR}/app:/app
    command: sh -c "npm install && node ."
    ports:
      - "4000:4000"
    restart: always