version: "3.7"

services:
  server:
    image: python:3.11-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/app:/app
      - ${UMBREL_ROOT}/app-data:/umbrel-app-data
    working_dir: /app
    command: [
      "sh", "-c",
      "pip install --no-cache-dir -r requirements.txt && python app.py"
    ]
    environment:
      - UMBREL_APP_DATA_DIR=/umbrel-app-data
    ports:
      - "8080:8080"
