version: "3.7"

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/app/data/config.json:/etc/v2ray/config.json
    ports:
      - "10086:10086"
    command: run -c /etc/v2ray/config.json

  web:
    image: node:18-alpine
    container_name: v2ray-ui
    working_dir: /app
    volumes:
      - ${APP_DATA_DIR}/app:/app
    command: sh -c "npm install express && node ."
    ports:
      - "3000:3000"
    restart: always