version: "3.7"

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: on-failure
    volumes:
      - ./data/config.json:/etc/v2ray/config.json
    ports:
      - "10086:10086"
    command: run -c /etc/v2ray/config.json

  web:
    build: ./api
    container_name: v2ray-ui
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./api:/app/api
      - ./ui:/app/ui
    restart: always